name: flutter_expenses_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  month_picker_strip: ^0.0.3
  flutter_datetime_picker: ^1.3.4
  sqflite: ^1.1.7+3
  path: ^1.6.4
  synchronized: ^2.1.0+2
  keyboard_actions: ^3.2.0
  table_calendar: ^2.2.2
  shared_preferences: ^0.5.6+1

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
